### ISSUE TITLE
Any plan for the "Perpetual Humanoid Control" part?

### ISSUE THREAD

**Issue by xjwxjw** [ZhengyiLuo/UniversalHumanoidControl#13]
Amazing work! Looking forward to the "Perpetual Humanoid Control" part :)

**Comment by ZhengyiLuo** [comment]
It's in progress! The difficult part is bringing the AMP pipeline from Isaac to Mujoco; the two simulator's code structure is rather different since one uses parallel GPU simulation and another one multi-thread CPU simulation. I am trying to chip it away bit by bit. 

Also PHC will (hopefully) be open-sourced, so maybe directly transiting to Isaac is also an viable option.
