### ISSUE TITLE
Unable to run process_amass_db.py

### ISSUE THREAD

**Issue by ethanluoyc** [ZhengyiLuo/UniversalHumanoidControl#29]
Hi Zhengyi,

Thanks for sharing this repo.

I am trying to setup training with this codebase. However, I am a bit confused with how to set up the models for running process_amass_db.py

In particular, it wasn't clear to me how to set up the models for SMPL-H. In `process_amass_db.py` you used the SMPLH parser for male, female and neutral but am unsure how to obtain those

There are a few issues with current instructions.
1. The link in the README.md for SMPL-H is invalid. I believe you mean https://mano.is.tue.mpg.de/index.html as opposed to https://smpl.is.tue.mpg.de/downloads ?
2. In the MANO download section, there were both the _Model & Code_ download and the Extended SMPL+H model download. In the former, I can find some pkl files with name SMPLH_female and SMPLH_male but there is no neutral. In the _Extended SMPL+H_ download I can find male female and neutral but those are in npz format instead of pkl. Can you kindly clarify how to prepare the models used for training the UHC controller?

Best,
Yicheng

**Comment by ZhengyiLuo** [comment]
Ahhh, right it should be in [Mano](https://mano.is.tue.mpg.de/download.php), search for "[Extended SMPL+H model](https://download.is.tue.mpg.de/download.php?domain=mano&resume=1&sfile=smplh.tar.xz)  (used in [AMASS](https://amass.is.tuebingen.mpg.de/) project)". 

You can specify the npz the SMPL_parser (might need some modifications). Or you can directly use the SMPL parser since the body shape of SMPL and SMPLH are compatible. 

You can refer to the (basically same file) [process in PHC](https://github.com/ZhengyiLuo/PerpetualHumanoidControl/blob/master/scripts/data_process/process_amass_db.py), which I have improved.
